#!/bin/bash
export PATH=$HOME/devel/qemu_optee/toolchains/aarch32/bin:$PATH

export TA_DEV_KIT_DIR=$HOME/devel/qemu_optee/optee_os/out/arm32-plat-vexpress/export-user_ta
export TEEC_EXPORT=$HOME/devel/qemu_optee/optee_client/out/export
export PLATFORM=vexpress
export PLATFORM_FLAVOR=qemu_virt

cd $HOME/devel/qemu_optee/comcast_cryptoapi_ta_example
make O=$HOME/devel/qemu_optee/out/comcast_ta \
                HOST_CROSS_COMPILE=arm-linux-gnueabihf- \
                TA_CROSS_COMPILE=arm-linux-gnueabihf- \
                $@
