#!/bin/bash
export PATH=$HOME/devel/fvp_optee/toolchains/aarch64/bin:$PATH
export PATH=$HOME/devel/fvp_optee/toolchains/aarch32/bin:$PATH

export TA_DEV_KIT_DIR=$HOME/devel/fvp_optee/optee_os/out-os-fvp/export-user_ta
export TEEC_EXPORT=$HOME/devel/fvp_optee/optee_client/out-client-aarch64/export

cd $HOME/devel/fvp_optee/comcast_cryptoapi_ta_example
make O=./out-client-aarch64 \
                HOST_CROSS_COMPILE=aarch64-linux-gnu- \
                TA_CROSS_COMPILE=arm-linux-gnueabihf- \
                $@
