#!/bin/bash
# To get this to work, you should have things setup according to the repo setup
# described on optee_os GitHub pages.
OPTEE_ROOT=`pwd`/..

export PATH=$OPTEE_ROOT/toolchains/aarch32/bin:$PATH
export PATH=$OPTEE_ROOT/toolchains/aarch64/bin:$PATH

ARCH32_CROSS_COMPILER=arm-linux-gnueabihf-
ARCH64_CROSS_COMPILER=aarch64-linux-gnu-

case $TARGET in
	qemu)
		export PLATFORM=vexpress
		export PLATFORM_FLAVOR=qemu_virt
		TA_ARCH=arm32
		HOST_CROSS_COMPILE=$ARCH32_CROSS_COMPILER
		TA_CROSS_COMPILE=$ARCH32_CROSS_COMPILER
		;;
	fvp)
		export PLATFORM=vexpress
		export PLATFORM_FLAVOR=qemu_virt
		TA_ARCH=arm32
		HOST_CROSS_COMPILE=$ARCH64_CROSS_COMPILER
		TA_CROSS_COMPILE=$ARCH32_CROSS_COMPILER
		;;
	*)
		echo "Not supported"
		exit
esac

export TA_DEV_KIT_DIR=$OPTEE_ROOT/optee_os/out/arm-plat-$PLATFORM/export-ta_$TA_ARCH
export TEEC_EXPORT=$OPTEE_ROOT/optee_client/out/export

cd $OPTEE_ROOT/comcast_cryptoapi_ta_example
make O=$OPTEE_ROOT/out/comcast_ta \
                HOST_CROSS_COMPILE=$HOST_CROSS_COMPILE \
                TA_CROSS_COMPILE=$TA_CROSS_COMPILE \
                $@
